# Generated by Django 6.0.7 on 2026-07-22 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('host', 'Host'), ('participant', 'Participant')], default='participant', max_length=20)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('admitted', 'Admitted'), ('rejected', 'Rejected'), ('left', 'Left')], default='waiting', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('admitted_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meetings.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
                'constraints': [models.UniqueConstraint(fields=('meeting', 'user'), name='unique_user_per_meeting')],
            },
        ),
    ]
