# Generated by Django 6.0.7 on 2026-07-23 09:14

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meetingparticipant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Planned meeting duration between 15 and 480 minutes.', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(480)]),
        ),
        migrations.AddField(
            model_name='meeting',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='Leave empty for an instant meeting.', null=True),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['status', 'scheduled_at'], name='meeting_status_schedule_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['host', 'status'], name='meeting_host_status_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingparticipant',
            index=models.Index(fields=['meeting', 'status'], name='participant_meeting_status_idx'),
        ),
    ]
